var searchData=
[
  ['banner',['Banner',['../namespaceapfel.html#a4c2d1010b19712c8c950c6aed5db7c98',1,'apfel']]],
  ['beta',['Beta',['../structapfel_1_1TmdObjects.html#abc3e9dcd0597fa0f2bbedfc236de2364',1,'apfel::TmdObjects']]],
  ['beta0',['beta0',['../namespaceapfel.html#ad7d8f0a66ec8fcbf48618e9fbecb86aa',1,'apfel']]],
  ['beta1',['beta1',['../namespaceapfel.html#a9011b2307d53e5b7304c7222d5d8f7b1',1,'apfel']]],
  ['beta2',['beta2',['../namespaceapfel.html#a5854e1781e2511935c66f5348a22e4d0',1,'apfel']]],
  ['beta3',['beta3',['../namespaceapfel.html#a398e0f40cc355e7384e034d0ffccc2b0',1,'apfel']]],
  ['betaqcd',['betaQCD',['../classapfel_1_1AlphaQCD.html#a8399fbe2c22eedd5c27d5c11304ce543',1,'apfel::AlphaQCD']]],
  ['betaqcd_2eh',['betaqcd.h',['../betaqcd_8h.html',1,'']]],
  ['builddglap',['BuildDglap',['../namespaceapfel.html#a18028890407af59b225ad50b335ec6cd',1,'apfel::BuildDglap(map&lt; int, DglapObjects &gt; const &amp;DglapObj, function&lt; map&lt; int, double &gt;(double const &amp;, double const &amp;)&gt; const &amp;InDistFunc, double const &amp;MuRef, int const &amp;PerturbativeOrder, function&lt; double(double const &amp;)&gt; const &amp;Alphas, int const &amp;nsteps=10)'],['../namespaceapfel.html#a0adfe8d477547c5555d70d1ee8854fd3',1,'apfel::BuildDglap(map&lt; int, DglapObjects &gt; const &amp;DglapObj, double const &amp;MuRef, int const &amp;PerturbativeOrder, function&lt; double(double const &amp;)&gt; const &amp;Alphas, int const &amp;nsteps=10)'],['../namespaceapfel.html#a0d5da08ef505817b5050f8d8d7189706',1,'apfel::BuildDglap(function&lt; DglapObjects(double const &amp;)&gt; const &amp;DglapObj, vector&lt; double &gt; const &amp;Thresholds, function&lt; map&lt; int, double &gt;(double const &amp;, double const &amp;)&gt; const &amp;InDistFunc, double const &amp;MuRef, int const &amp;PerturbativeOrder, function&lt; double(double const &amp;)&gt; const &amp;Alphas, int const &amp;nsteps=10)']]],
  ['buildstructurefunctions',['BuildStructureFunctions',['../namespaceapfel.html#a2b5402376aaae6b7c81c5d51c9fccf5e',1,'apfel::BuildStructureFunctions(function&lt; StructureFunctionObjects(double const &amp;, vector&lt; double &gt; const &amp;)&gt; const &amp;FObj, function&lt; map&lt; int, double &gt;(double const &amp;, double const &amp;)&gt; const &amp;InDistFunc, int const &amp;PerturbativeOrder, function&lt; double(double const &amp;)&gt; const &amp;Alphas, function&lt; vector&lt; double &gt;(double const &amp;)&gt; const &amp;Couplings)'],['../namespaceapfel.html#ae76ef32ffd2cc59eff2bf72791d027a9',1,'apfel::BuildStructureFunctions(function&lt; StructureFunctionObjects(double const &amp;, vector&lt; double &gt; const &amp;)&gt; const &amp;FObj, function&lt; double(int const &amp;, double const &amp;, double const &amp;)&gt; const &amp;InDistFunc, int const &amp;PerturbativeOrder, function&lt; double(double const &amp;)&gt; const &amp;Alphas, function&lt; vector&lt; double &gt;(double const &amp;)&gt; const &amp;Couplings)']]],
  ['buildtmdffs',['BuildTmdFFs',['../namespaceapfel.html#a36f72df715a67209ecf3f1aa7b24b0ac',1,'apfel']]],
  ['buildtmdpdfs',['BuildTmdPDFs',['../namespaceapfel.html#ad1e8db488674324ecfabc5a55ec596b8',1,'apfel']]]
];
