var searchData=
[
  ['banner',['Banner',['../namespaceapfel.html#a4c2d1010b19712c8c950c6aed5db7c98',1,'apfel']]],
  ['beta',['Beta',['../structapfel_1_1TmdObjects.html#ab03e9049059c37249865f48ed48dce68',1,'apfel::TmdObjects']]],
  ['beta0',['beta0',['../namespaceapfel.html#ad7d8f0a66ec8fcbf48618e9fbecb86aa',1,'apfel']]],
  ['beta1',['beta1',['../namespaceapfel.html#a9011b2307d53e5b7304c7222d5d8f7b1',1,'apfel']]],
  ['beta2',['beta2',['../namespaceapfel.html#a5854e1781e2511935c66f5348a22e4d0',1,'apfel']]],
  ['beta3',['beta3',['../namespaceapfel.html#a398e0f40cc355e7384e034d0ffccc2b0',1,'apfel']]],
  ['betaqcd',['betaQCD',['../classapfel_1_1AlphaQCD.html#a8399fbe2c22eedd5c27d5c11304ce543',1,'apfel::AlphaQCD']]],
  ['betaqcd_2eh',['betaqcd.h',['../betaqcd_8h.html',1,'']]],
  ['builddglap',['BuildDglap',['../namespaceapfel.html#ad66196392cf742bfd93e1faeedaf3e0b',1,'apfel::BuildDglap(std::map&lt; int, DglapObjects &gt; const &amp;DglapObj, std::function&lt; std::map&lt; int, double &gt;(double const &amp;, double const &amp;)&gt; const &amp;InDistFunc, double const &amp;MuRef, int const &amp;PerturbativeOrder, std::function&lt; double(double const &amp;)&gt; const &amp;Alphas, int const &amp;nsteps=10)'],['../namespaceapfel.html#ad827529766bae9922f962aadf3c2fc87',1,'apfel::BuildDglap(std::map&lt; int, DglapObjects &gt; const &amp;DglapObj, double const &amp;MuRef, int const &amp;PerturbativeOrder, std::function&lt; double(double const &amp;)&gt; const &amp;Alphas, int const &amp;nsteps=10)'],['../namespaceapfel.html#a6932c89112eac9fb319fcfdc5c0978a5',1,'apfel::BuildDglap(std::function&lt; DglapObjects(double const &amp;)&gt; const &amp;DglapObj, std::vector&lt; double &gt; const &amp;Thresholds, std::function&lt; std::map&lt; int, double &gt;(double const &amp;, double const &amp;)&gt; const &amp;InDistFunc, double const &amp;MuRef, int const &amp;PerturbativeOrder, std::function&lt; double(double const &amp;)&gt; const &amp;Alphas, int const &amp;nsteps=10)']]],
  ['buildstructurefunctions',['BuildStructureFunctions',['../namespaceapfel.html#a22f4cb2750a5c0cf78ed6e1b47d4f773',1,'apfel::BuildStructureFunctions(std::function&lt; StructureFunctionObjects(double const &amp;, std::vector&lt; double &gt; const &amp;)&gt; const &amp;FObj, std::function&lt; std::map&lt; int, double &gt;(double const &amp;, double const &amp;)&gt; const &amp;InDistFunc, int const &amp;PerturbativeOrder, std::function&lt; double(double const &amp;)&gt; const &amp;Alphas, std::function&lt; std::vector&lt; double &gt;(double const &amp;)&gt; const &amp;Couplings)'],['../namespaceapfel.html#a512b81465d3ac92e8a159cca82308766',1,'apfel::BuildStructureFunctions(std::function&lt; StructureFunctionObjects(double const &amp;, std::vector&lt; double &gt; const &amp;)&gt; const &amp;FObj, std::function&lt; double(int const &amp;, double const &amp;, double const &amp;)&gt; const &amp;InDistFunc, int const &amp;PerturbativeOrder, std::function&lt; double(double const &amp;)&gt; const &amp;Alphas, std::function&lt; std::vector&lt; double &gt;(double const &amp;)&gt; const &amp;Couplings)']]],
  ['buildtmdffs',['BuildTmdFFs',['../namespaceapfel.html#a94755164d5487835bc83471bd7689fa1',1,'apfel']]],
  ['buildtmdpdfs',['BuildTmdPDFs',['../namespaceapfel.html#a7af6bb4cb44415bd0cd14c569db229ba',1,'apfel']]]
];
