var searchData=
[
  ['main_2edox',['main.dox',['../main_8dox.html',1,'']]],
  ['massivecoefficientfunctions_2eh',['massivecoefficientfunctions.h',['../massivecoefficientfunctions_8h.html',1,'']]],
  ['massivezerocoefficientfunctions_2eh',['massivezerocoefficientfunctions.h',['../massivezerocoefficientfunctions_8h.html',1,'']]],
  ['matching_20convolution_20maps',['Matching convolution maps',['../group__MatchBases.html',1,'']]],
  ['matchedevolution',['MatchedEvolution',['../classapfel_1_1MatchedEvolution.html',1,'apfel::MatchedEvolution&lt; T &gt;'],['../classapfel_1_1MatchedEvolution.html#adb2660fb7842ff7cfd1babfcdb2b0a05',1,'apfel::MatchedEvolution::MatchedEvolution()=delete'],['../classapfel_1_1MatchedEvolution.html#aebbd27d9fa7dc916378a4b4d726b5d26',1,'apfel::MatchedEvolution::MatchedEvolution(T const &amp;ObjRef, double const &amp;MuRef, std::vector&lt; double &gt; const &amp;Thresholds, int const &amp;nsteps=10)']]],
  ['matchedevolution_2eh',['matchedevolution.h',['../matchedevolution_8h.html',1,'']]],
  ['matchedevolution_3c_20double_20_3e',['MatchedEvolution&lt; double &gt;',['../classapfel_1_1MatchedEvolution.html',1,'apfel']]],
  ['matchedevolution_3c_20set_3c_20t_20_3e_20_3e',['MatchedEvolution&lt; Set&lt; T &gt; &gt;',['../classapfel_1_1MatchedEvolution.html',1,'apfel']]],
  ['matchevoloperatorbasisqcd',['MatchEvolOperatorBasisQCD',['../classapfel_1_1MatchEvolOperatorBasisQCD.html',1,'apfel::MatchEvolOperatorBasisQCD'],['../classapfel_1_1MatchEvolOperatorBasisQCD.html#ae332069e80f8b3ce1ecdd2d0dff9a19c',1,'apfel::MatchEvolOperatorBasisQCD::MatchEvolOperatorBasisQCD()']]],
  ['matchingbasisqcd',['MatchingBasisQCD',['../classapfel_1_1MatchingBasisQCD.html',1,'apfel::MatchingBasisQCD'],['../classapfel_1_1MatchingBasisQCD.html#a9dc8f980a586c204b52dfff6626b78ae',1,'apfel::MatchingBasisQCD::MatchingBasisQCD()']]],
  ['matchingbasisqcd_2eh',['matchingbasisqcd.h',['../matchingbasisqcd_8h.html',1,'']]],
  ['matchingconditions',['MatchingConditions',['../structapfel_1_1DglapObjects.html#af679b08b27ced9c1f3d630716fb801a0',1,'apfel::DglapObjects']]],
  ['matchingconditions_2eh',['matchingconditions.h',['../matchingconditions_8h.html',1,'']]],
  ['matchingconditions_5ftl_2eh',['matchingconditions_tl.h',['../matchingconditions__tl_8h.html',1,'']]],
  ['matchingfunctions_2eh',['matchingfunctions.h',['../matchingfunctions_8h.html',1,'']]],
  ['matchingfunctionsffs',['MatchingFunctionsFFs',['../structapfel_1_1TmdObjects.html#ad4e89eb5cdc9c52c7177070732e912ca',1,'apfel::TmdObjects']]],
  ['matchingfunctionspdfs',['MatchingFunctionsPDFs',['../structapfel_1_1TmdObjects.html#a5db836a1e6ef90ce6abf408c0ac6602f',1,'apfel::TmdObjects']]],
  ['matchingoperatorbasisqcd',['MatchingOperatorBasisQCD',['../classapfel_1_1MatchingOperatorBasisQCD.html',1,'apfel::MatchingOperatorBasisQCD'],['../classapfel_1_1MatchingOperatorBasisQCD.html#a891d84b83ee0ecc589a5f3833e54852f',1,'apfel::MatchingOperatorBasisQCD::MatchingOperatorBasisQCD()']]],
  ['matchobject',['MatchObject',['../classapfel_1_1AlphaQCD.html#a2d1c556fa5a4173f3577234e4615192e',1,'apfel::AlphaQCD::MatchObject()'],['../classapfel_1_1Dglap.html#ac9f37328fb2680f5b1be74a279428972',1,'apfel::Dglap::MatchObject()'],['../classapfel_1_1MatchedEvolution.html#a82f4e0ff82cd9b5f1e393625b4d81bc4',1,'apfel::MatchedEvolution::MatchObject()']]],
  ['matchtmdffs',['MatchTmdFFs',['../namespaceapfel.html#a5cafd89bab82404508df1bf81e023c15',1,'apfel']]],
  ['matchtmdpdfs',['MatchTmdPDFs',['../namespaceapfel.html#afee5fecc01a4ed7d468c5884965d4df0',1,'apfel']]],
  ['matrix',['matrix',['../classapfel_1_1matrix.html',1,'apfel::matrix&lt; T &gt;'],['../classapfel_1_1matrix.html#ad233ffd5afb1d9ec9ba46a39202338b1',1,'apfel::matrix::matrix()']]],
  ['matrix_2eh',['matrix.h',['../matrix_8h.html',1,'']]],
  ['matrix_3c_20double_20_3e',['matrix&lt; double &gt;',['../classapfel_1_1matrix.html',1,'apfel']]],
  ['messages_2eh',['messages.h',['../messages_8h.html',1,'']]],
  ['massless_20limit_20of_20the_20massive_20neutral_20current_20coefficient_20functions',['Massless limit of the massive neutral current coefficient functions',['../group__NCMassiveZero.html',1,'']]]
];
